#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-powerpack
Version  : 0.1.1
Release  : 3
URL      : https://rubygems.org/downloads/powerpack-0.1.1.gem
Source0  : https://rubygems.org/downloads/powerpack-0.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubygems-tasks

%description
[![Gem Version](https://badge.fury.io/rb/powerpack.png)](http://badge.fury.io/rb/powerpack)
[![Build Status](https://travis-ci.org/bbatsov/powerpack.png?branch=master)](https://travis-ci.org/bbatsov/powerpack)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n powerpack-0.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-powerpack.gemspec

%build
gem build rubygem-powerpack.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
powerpack-0.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/powerpack-0.1.1
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/powerpack-0.1.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Array/butfirst-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Array/butlast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/average-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/cdesc-Enumerable.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/drop_last-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/drop_last_while-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/exactly%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/frequencies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/several%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/sum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/take_last-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Enumerable/take_last_while-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Hash/symbolize_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/billion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/hundred-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/million-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/neg%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/pos%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/quadrillion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/thousand-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Numeric/trillion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/Powerpack/cdesc-Powerpack.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/ascii_only%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/ascii_only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/blank%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove_prefix%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove_prefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove_suffix%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/remove_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/squish%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/squish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/strip_indent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/String/strip_margin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/powerpack-0.1.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/array.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/array/butfirst.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/array/butlast.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/average.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/drop_last.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/drop_last_while.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/exactly.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/frequencies.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/several.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/sum.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/take_last.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/enumerable/take_last_while.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/hash/symbolize_keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/numeric.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/numeric/neg.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/numeric/pos.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/numeric/scale.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/ascii_only.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/blank.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/format.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/remove.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/remove_prefix.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/remove_suffix.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/squish.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/strip_indent.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/string/strip_margin.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/lib/powerpack/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/powerpack.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/array/butfirst_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/array/butlast_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/average_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/drop_last_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/drop_last_while_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/exactly_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/frequencies_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/several_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/sum_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/take_last_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/enumerable/take_last_while_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/hash/symbolize_keys_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/numeric/neg_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/numeric/pos_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/numeric/scale_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/ascii_only_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/blank_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/format_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/remove_prefix_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/remove_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/remove_suffix_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/squish_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/strip_indent_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/powerpack/string/strip_margin_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/powerpack-0.1.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/powerpack-0.1.1.gemspec
